export const legendsData = [
    
    { "id": "bangalore", "name": "バンガロール", "classname": "assault", "imgLink": "./images/legendsImage/Bangalore.avif", "isActive": true },
    { "id": "revenant", "name": "レブナント", "classname": "assault", "imgLink": "./images/legendsImage/Revenant.avif", "isActive": true },
    { "id": "fuse", "name": "ヒューズ", "classname": "assault", "imgLink": "./images/legendsImage/Fuse.avif", "isActive": true },
    { "id": "mad-maggie", "name": "マッドマギー", "classname": "assault", "imgLink": "./images/legendsImage/MadMaggie.avif", "isActive": true },
    { "id": "ballistic", "name": "バリスティック", "classname": "assault", "imgLink": "./images/legendsImage/Ballistic.avif", "isActive": true },

    { "id": "pathfinder", "name": "パスファインダー", "classname": "skirmisher", "imgLink": "./images/legendsImage/Pathfinder.avif", "isActive": true },
    { "id": "wraith", "name": "レイス", "classname": "skirmisher", "imgLink": "./images/legendsImage/Wraith.avif", "isActive": true },
    { "id": "octane", "name": "オクタン", "classname": "skirmisher", "imgLink": "./images/legendsImage/Octane.avif", "isActive": true },
    { "id": "horizon", "name": "ホライゾン", "classname": "skirmisher", "imgLink": "./images/legendsImage/Horizon.avif", "isActive": true },
    { "id": "ash", "name": "アッシュ", "classname": "skirmisher", "imgLink": "./images/legendsImage/Ash.avif", "isActive": true },
    { "id": "alter", "name": "オルター", "classname": "skirmisher", "imgLink": "./images/legendsImage/Alter.avif", "isActive": true },
    { "id": "axle", "name": "アクセル", "classname": "skirmisher", "imgLink": "./images/legendsImage/Axle.avif", "isActive": true },

    { "id": "bloodhound", "name": "ブラッドハウンド", "classname": "recon", "imgLink": "./images/legendsImage/Bloodhound.avif", "isActive": true },
    { "id": "crypto", "name": "クリプト", "classname": "recon", "imgLink": "./images/legendsImage/Crypto.avif", "isActive": true },
    { "id": "valkyrie", "name": "ヴァルキリー", "classname": "recon", "imgLink": "./images/legendsImage/Valkyrie.avif", "isActive": true },
    { "id": "seer", "name": "シア", "classname": "recon", "imgLink": "./images/legendsImage/Seer.avif", "isActive": true },
    { "id": "vantage", "name": "ヴァンテージ", "classname": "recon", "imgLink": "./images/legendsImage/Vantage.avif", "isActive": true },
    { "id": "sparrow", "name": "スパロー", "classname": "recon", "imgLink": "./images/legendsImage/sparrow.avif", "isActive": true },

    { "id": "gibraltar", "name": "ジブラルタル", "classname": "support", "imgLink": "./images/legendsImage/Gibraltar.avif", "isActive": true },
    { "id": "lifeline", "name": "ライフライン", "classname": "support", "imgLink": "./images/legendsImage/Lifeline.avif", "isActive": true },
    { "id": "mirage", "name": "ミラージュ", "classname": "support", "imgLink": "./images/legendsImage/Mirage.avif", "isActive": true },
    { "id": "loba", "name": "ローバ", "classname": "support", "imgLink": "./images/legendsImage/Loba.avif", "isActive": true },
    { "id": "newcastle", "name": "ニューキャッスル", "classname": "support", "imgLink": "./images/legendsImage/Newcastle.avif", "isActive": true },
    { "id": "conduit", "name": "コンジット", "classname": "support", "imgLink": "./images/legendsImage/Conduit.avif", "isActive": true },

    { "id": "caustic", "name": "コースティック", "classname": "controller", "imgLink": "./images/legendsImage/Caustic.avif", "isActive": true },
    { "id": "wattson", "name": "ワットソン", "classname": "controller", "imgLink": "./images/legendsImage/Wattson.avif", "isActive": true },
    { "id": "rampart", "name": "ランパート", "classname": "controller", "imgLink": "./images/legendsImage/Rampart.avif", "isActive": true },
    { "id": "catalyst", "name": "カタリスト", "classname": "controller", "imgLink": "./images/legendsImage/Catalyst.avif", "isActive": true },
]


const rawWeaponsData = [
  {
    "id": "Havoc",
    "name": "ハボック",
    "type": "AR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Havoc.png",
  },
  {
    "id": "Flatline",
    "name": "フラットライン",
    "type": "AR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Flatline.png",
  },
  {
    "id": "Hemlok",
    "name": "ヘムロック",
    "type": "AR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Hemlok.png",
  },
  {
    "id": "R-301",
    "name": "R-301",
    "type": "AR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/R-301.png",
  },
  {
    "id": "Nemesis",
    "name": "ネメシス",
    "type": "AR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Nemesis.png",
  },
  {
    "id": "Alternator",
    "name": "オルタネーター",
    "type": "SMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Alternator.png",
  },
  {
    "id": "Prowler",
    "name": "プラウラー",
    "type": "SMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Prowler.png",
  },
  {
    "id": "R-99",
    "name": "R-99",
    "type": "SMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/R-99.png",
  },
  {
    "id": "Volt",
    "name": "ボルト",
    "type": "SMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Volt.png",
  },
  {
    "id": "CAR",
    "name": "CAR",
    "type": "SMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/CAR.png",
  },
  {
    "id": "Rampage",
    "name": "ランページ",
    "type": "LMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Rampage.png",
  },
  {
    "id": "Spitfire",
    "name": "スピットファイア",
    "type": "LMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Spitfire.png",
  },
  {
    "id": "L-STAR",
    "name": "Lスター",
    "type": "LMG",
    "isCarePackage": "TRUE",
    "canBeSling": "FALSE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/L-STAR.png",
  },
  {
    "id": "Divotion",
    "name": "ディヴォーション",
    "type": "LMG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Divotion.png",
  },
  {
    "id": "ChargeRifle",
    "name": "チャージライフル",
    "type": "SR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,6x,4-8x,1x_digi,1x_holo,4-10x,",
    "imgLink": "./images/weaponsImage/ChargeRifle.png",
  },
  {
    "id": "Longbow",
    "name": "ロングボウ",
    "type": "SR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,6x,4-8x,1x_digi,1x_holo,4-10x,",
    "imgLink": "./images/weaponsImage/Longbow.png",
  },
  {
    "id": "Kraber",
    "name": "クレーバー",
    "type": "SR",
    "isCarePackage": "TRUE",
    "canBeSling": "FALSE",
    "canAkimbo": "FALSE",
    "scope": "default",
    "imgLink": "./images/weaponsImage/Kraber.png",
  },
  {
    "id": "Sentinel",
    "name": "センチネル",
    "type": "SR",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,6x,4-8x,1x_digi,1x_holo,4-10x,",
    "imgLink": "./images/weaponsImage/Sentinel.png",
  },
  {
    "id": "EVA-8",
    "name": "EVA-8",
    "type": "SG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/EVA-8.png",
  },
  {
    "id": "Mastiff",
    "name": "マスティフ",
    "type": "SG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Mastiff.png",
  },
  {
    "id": "Mozambique",
    "name": "モザンビーク",
    "type": "SG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "TRUE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Mozambique.png",
  },
  {
    "id": "Peacekeeper",
    "name": "ピースキーパー",
    "type": "SG",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Peacekeeper.png",
  },
  {
    "id": "G7-scout",
    "name": "G7スカウト",
    "type": "marksman",
    "isCarePackage": "TRUE",
    "canBeSling": "FALSE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/G7-scout.png",
  },
  {
    "id": "Triple-Take",
    "name": "トリプルテイク",
    "type": "marksman",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Triple-Take.png",
  },
  {
    "id": "30-30Repeater",
    "name": "30-30リピーター",
    "type": "marksman",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/30-30Repeater.png",
  },
  {
    "id": "Bocek",
    "name": "ボセック",
    "type": "marksman",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,3x,1-2x,2-4x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Bocek.png",
  },
  {
    "id": "RE-45",
    "name": "RE-45",
    "type": "pistol",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/RE-45.png",
  },
  {
    "id": "P2020",
    "name": "P2020",
    "type": "pistol",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "TRUE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/P2020.png",
  },
  {
    "id": "Wingman",
    "name": "ウィングマン",
    "type": "pistol",
    "isCarePackage": "FALSE",
    "canBeSling": "TRUE",
    "canAkimbo": "FALSE",
    "scope": "1x,2x,1-2x,1x_digi,1x_holo,",
    "imgLink": "./images/weaponsImage/Wingman.png",
  }
]

export const weaponsData = rawWeaponsData.map(weapon => {
  return {
    ...weapon,
    isCarePackage: weapon.isCarePackage === "TRUE",
    canBeSling: weapon.canBeSling === "TRUE",
    canAkimbo: weapon.canAkimbo === "TRUE",
    scope: weapon.scope.replace(/,$/, "").split(',')
  };
});